# Generated by Django 5.2.3 on 2025-06-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao', models.CharField(max_length=5)),
                ('re', models.CharField(max_length=8, unique=True)),
                ('nome_guerra', models.CharField(max_length=200)),
                ('pelotao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pessoa', models.IntegerField(default=0)),
                ('carros', models.IntegerField(default=0)),
                ('motos', models.IntegerField(default=0)),
                ('qnt_ocorrencias', models.IntegerField(default=0)),
                ('flagrantes', models.IntegerField(default=0)),
                ('autuacoes', models.IntegerField(default=0)),
                ('raia', models.IntegerField(default=0)),
                ('procurado', models.IntegerField(default=0)),
                ('carro_apreendido', models.IntegerField(default=0)),
                ('moto_apreendida', models.IntegerField(default=0)),
                ('flagrantes_outros', models.IntegerField(default=0)),
                ('arma', models.IntegerField(default=0)),
                ('escolas', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policial')),
            ],
        ),
    ]
