# Generated by Django 4.2.23 on 2025-06-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producao_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='carros_aisp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producao',
            name='flagrantes_aisp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producao',
            name='motos_aisp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producao',
            name='pessoas_aisp',
            field=models.IntegerField(default=0),
        ),
    ]
