# Generated by Django 5.2.3 on 2025-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producao_carros_aisp_producao_flagrantes_aisp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacaoPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📤 Exportar Dados',
                'verbose_name_plural': '📤 Exportar Dados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Ver Ranking',
                'verbose_name_plural': '📊 Ver Ranking',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='policial',
            options={'verbose_name': 'Policial', 'verbose_name_plural': '👮 Cadastro de Policiais'},
        ),
        migrations.AlterModelOptions(
            name='producao',
            options={'verbose_name': 'Produção', 'verbose_name_plural': '➕ Cadastrar Produção'},
        ),
    ]
