# Generated by Django 5.2.3 on 2025-08-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exportacaoplaceholder_rankingplaceholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('estagio', 'Estágio')], max_length=10)),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formacao')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policial')),
            ],
            options={
                'unique_together': {('policial', 'formacao')},
            },
        ),
    ]
