# Generated by Django 5.2.3 on 2025-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formacao_participacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeProdutividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelotao', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('pessoa', models.IntegerField(default=0)),
                ('carros', models.IntegerField(default=0)),
                ('motos', models.IntegerField(default=0)),
                ('pessoas_aisp', models.IntegerField(default=0)),
                ('carros_aisp', models.IntegerField(default=0)),
                ('motos_aisp', models.IntegerField(default=0)),
                ('qnt_ocorrencias', models.IntegerField(default=0)),
                ('flagrantes', models.IntegerField(default=0)),
                ('flagrantes_aisp', models.IntegerField(default=0)),
                ('autuacoes', models.IntegerField(default=0)),
                ('raia', models.IntegerField(default=0)),
                ('procurado', models.IntegerField(default=0)),
                ('carro_apreendido', models.IntegerField(default=0)),
                ('moto_apreendida', models.IntegerField(default=0)),
                ('flagrantes_outros', models.IntegerField(default=0)),
                ('arma', models.IntegerField(default=0)),
                ('escolas', models.IntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('policiais', models.ManyToManyField(to='core.policial')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': '📋 Lançamento por Equipe',
            },
        ),
    ]
